### PR TITLE
feat: add sensor Entities and descriptors

### PR DESCRIPTION
**Pull request by petrleocompel**
- Exchanged `Entity` for `SensorEntity`
- added Sensor Entity descriptors

Now HA have temperature and humidity as graphs.
Same could be done with others. It was drunk quick fix during **garage session**. For @vasule

I plan to make a bigger clean up later. (old typings, split in files etc...)

### CODE REVIEW

**Comment by CestLaGalere** [comment]
I have merged this and it now gives an unknown error when I try and update the integration in HACS

**Comment by petrleocompel** [comment]
The reason will be pr #4 -> 

In configuration.yml you have to correct the "mobilealerts" to "mobile_alerts".
Later during any display it will use correct domain and icon from "home assistant" brands

**Comment by CestLaGalere** [comment]
ah - my bad for not reading this thoroughly enough! Many thanks - do you want permissions to merge (I assume that's admin)?

**Comment by petrleocompel** [comment]
That is up to you.
Currently there is more to enable. `Github Actions` would check for validity of manifest and basic installation. Later can do automatic tests.

**Pull request merged**
